- name: conditions
  hosts: localhost
  vars:
    a: abc
    b: 10
    c: true
    d: false
  tasks:
    - name: conditions on strings
      debug:
        msg: String condition is true
      when: a == 'abc'

    - name: conditions on strings
      debug:
        msg: String condition is not true
      when: a != 'abc'

# Variable should always come left side

    - name: number1
      debug:
        msg: both numbers are equal
      when: b == 10
    - name: number1
      debug:
        msg: b is less than 20
      when: b < 20

    - name: boolean1
      debug:
        msg: b is true
      when: c
    - name: boolean1
      debug:
        msg: d is false
      when: not d