#- name: Setup Forntend Component
#  hosts: frontend
#  gather_facts: no
#  become: yes
#  roles:
#    - frontend
#
#- name: Setup mongodb Component
#  hosts: mongodb
#  gather_facts: no
#  become: yes
#  roles:
#    - mongodb
#
#- name: Setup catalogue Component
#  hosts: catalogue
#  gather_facts: no
#  become: yes
#  roles:
#    - catalogue


- name: Roboshop setup
  hosts: "{{hosts}}"
  gather_facts: no
  become: yes
  roles:
    - "{{role_name}}"