#If we declare the variable at play level all the tasks will accept the variable.

- name: play level variables
  hosts: prd
  vars:
    url: chakra.pizza.com
  tasks:
    - name: prind URL
      ansible.builtin.debug:
        msg: url = {{url}}

 #Task level variable, scope of the variable is only for this task.
    - name: print task level URL
      vars:
        url: google.com
      ansible.builtin.debug:
          msg: url = {{url}}
    - name: print task level URL
      ansible.builtin.debug:
        msg: url = {{url}}

#Variables from a file.
- name: play level variables
  hosts: prd
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print variables from file
      ansible.builtin.debug:
        msg: url = {{url}}

- name: inventory level variables
  hosts: prd
  tasks:
    - name: prind URL
      ansible.builtin.debug:
        msg: url = {{url}}

- name: Ansible facts
  hosts: dev
  tasks:
    - name: Architecture
      ansible.builtin.debug:
          msg: ansible_architecture = {{ansible_architecture}}, IP = {{ansible_default_ipv4.address}}

- name: Register variable
  hosts: dev
  tasks:
    - name: print hostname
      ansible.builtin.shell: uptime
      register: out
    - name: Set a fact
      ansible.builtin.set_fact:
        output: "{{out.stdout}}"
    - name: print output
      ansible.builtin.debug:
#        msg: "{{out.stdout}}"
#        msg: "{{out.stdout}}"
#        msg: "{{out.stdout_lines[0]}}"
         msg: "{{output}}"


#command level variable is using -e option
#gp; ansible-playbook -i inventory-sample 02-vars.yml -e url=example.com -ucentos -k

####Variable precedence from high to low
#command line variables
#task level variables
#play level variables
#inventory variables

##Pre-defined variables(FACTS), use setup module
#gp; ansible-playbook -i inventory-sample dev -m setup

##Use -e option to provide variables and passwords
#gp; ansible-playbook -i inventory-sample 02-vars.yml  -ucentos -e ansible_password=DevOps321
#gp; ansible-playbook -i inventory-sample 02-vars.yml  -e ansible_user=centos -e ansible_password=DevOps321

#Run time variables
#From task output (register)
#set a variable using task(set_fact)

#Next topic is roles
