- name: setup {{ component }} server
  import_role:
    name: common
    tasks_from: app-setup.yaml

- name: setup nodejs
  import_role:
    name: common
    tasks_from: nodejs.yaml

- name: copy {{ component }} service file
  template:
       src: "{{ component }}.service.j2"
       dest: /etc/systemd/system/catalogue.service
  notify: daemon reload

- name: copy repo of mongodb
  copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  package:
       name: mongodb-mongosh
       state: present

         #- name: connnect to mongodb catalogue
         #ansible.builtin.command: mongosh mongodb.chakra86.shop --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
         #register: catalogue_output

         #- name: load products into mongodb
         #  ansible.builtin.shell: mongosh --host mongodb.chakra86.shop </app/db/master-data.js
         #  when: catalogue_output.stdout | int < 0

- name: Start {{ component }} service
  import_role:
    name: common
    tasks_from: systemd_service.yaml
