---
- hosts: worker
  become: yes
  gather_facts: no
  tasks:
   - name: "{{ item }}"
     package:
       name: "{{ item }}"
       state: present
     loop:
       - nginx                                                                                         
       - mysql                                                                                         
       - httpd   

   - name: remove {{ item.name }}
     package:
       name: "{{ item.name }}"
       state: "{{ item.state }}"
     loop:
       - { name: "nginx", state: "absent" }
       - { name: "mysql", state: "absent" }
       - { name: "mysql", state: "absent" }

