---
- hosts: catalogue
  gather_facts: no
  become: yes
  tasks:
   - name: disable default module
     command: dnf module disable nodejs -y

   - name: enable module nodejs20
     command: dnf module enable nodejs:20 -y
   
   - name: install nodejs
     package:
      name: nodejs
      state: present

   - name: Create 'roboshop' with no login shell
     ansible.builtin.user:
        name: roboshop
        comment: "roboshop system user"
        shell: /sbin/nologin #  /sbin/nologin
        create_home: true # Create a home directory for the user
        home: /app
        system: true
        state: present
   
   - name: delete app directory
     file: 
       path: /app
       state: absent

   - name: create app directory
     file:
       state: directory
       path: /app
   
   - name: download app code
     get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
       dest: /app/catalogue-v3.zip

   - name: unzip the app code
     unarchive:
      src: /app/catalogue-v3.zip
      dest: /app/
      remote_src: yes
     
   - name: delete the catalogue zip filw
     file:
       path: /app/catalogue-v3.zip
       state: absent
   
   - name: install dependencies
     community.general.npm:
      path: /app

   - name: copy catalogue service file
     copy:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service

   - name: copy repo of mongodb
     copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongo.repo

   - name: install mongodb client
     package:
       name: mongodb-mongosh
       state: present


   - name: connnect to mongodb catalogue
     ansible.builtin.command: mongosh mongodb.chakra86.shop --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
     register: catalogue_output

   - name: load products into mongodb
     ansible.builtin.shell: mongosh --host mongodb.chakra86.shop </app/db/master-data.js
     when: catalogue_output.stdout | int < 0

   - name: start catalogue service
     systemd_service:
       name: catalogue
       enabled: yes
       daemon_reload: yes
       state: started
