---
- hosts: mysql
  gather_facts: no
  become: yes
  tasks:
   - name: install mysql
     dnf:
      name: mysql-server
      state: present

   - name: start mysql
     service:
       name: mysqld
       enabled: yes
       state: started

   - name: Change MySQL root password
     command: mysql_secure_installation --set-root-pass RoboShop@1

