   - name: add repo mongodb
     copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo 

   - name: install mongodb
     dnf:
      name: mongodb-org 
      state: present

   - name: update mongod.conf
     replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

   - name: start mongodb
     service:
      name: mongod
      enabled: yes
      state: started
