   - name: copy the repo file
     copy:
       src: rabbitmq.repo
       dest: /etc/yum.repos.d/rabbitmq.repo

   - name: install rabbitmq
     dnf:
      name: rabbitmq-server
      state: present

   - name: start rabbitmq
     service:
       name: rabbitmq-server
       enabled: yes
       state: started

   - name: Add RabbitMQ user and set permissions
     community.rabbitmq.rabbitmq_user:
      user: "{{ username }}""
      password: "{{ password }}"
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present