- name: setup {{ component }} server
  import_role:
    name: common
    tasks_from: app-setup.yaml

- name: setup nodejs
  import_role:
    name: common
    tasks_from: nodejs.yaml

- name: copy {{ component }} service file
  template:
       src: "{{ component }}.service.j2"
       dest: /etc/systemd/system/catalogue.service
  notify: daemon reload


- name: Start {{ component }} service
  import_role:
    name: common
    tasks_from: systemd_service.yaml
